-- INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('1984', 'George Orwell', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Sefiller', 'Victor Hugo', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Kürk Mantolu Madonna', 'Sabahattin Ali', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Beyaz Zambaklar Ülkesi', 'Grigory Petrov', 'Can Yayınları', 1);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Simyacı', 'Paulo Coelho', 'Can Yayınları', 5);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Suç ve Ceza', 'Fyodor Dostoyevski', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Tutunamayanlar', 'Oğuz Atay', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Hayvan Çiftliği', 'George Orwell', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('İnce Memed', 'Yaşar Kemal', 'Can Yayınları', 1);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Satranç', 'Stefan Zweig', 'Can Yayınları', 5);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Körlük', 'Jose Saramago', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Dönüşüm', 'Franz Kafka', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Fahrenheit 451', 'Ray Bradbury', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Martı', 'Richard Bach', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Uçurtma Avcısı', 'Khaled Hosseini', 'Can Yayınları', 5);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Bin Muhteşem Güneş', 'Khaled Hosseini', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Mülksüzler', 'Ursula K. Le Guin', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Yabancı', 'Albert Camus', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Dava', 'Franz Kafka', 'Can Yayınları', 1);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Aşk', 'Elif Şafak', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Baba ve Piç', 'Elif Şafak', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('İnsan Ne ile Yaşar', 'Tolstoy', 'Can Yayınları', 5);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Yeraltından Notlar', 'Fyodor Dostoyevski', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Çavdar Tarlasında Çocuklar', 'J. D. Salinger', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Serenad', 'Zülfü Livaneli', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Leyla’nın Evi', 'Zülfü Livaneli', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Balıkçı ve Oğlu', 'Zülfü Livaneli', 'Can Yayınları', 1);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Bilinmeyen Bir Kadının Mektubu', 'Stefan Zweig', 'Can Yayınları', 5);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Amok Koşucusu', 'Stefan Zweig', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Otomatik Portakal', 'Anthony Burgess', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Karanlığın Yüreği', 'Joseph Conrad', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Sineklerin Tanrısı', 'William Golding', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Saatleri Ayarlama Enstitüsü', 'Ahmet Hamdi Tanpınar', 'Can Yayınları', 5);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Huzur', 'Ahmet Hamdi Tanpınar', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Tehlikeli Oyunlar', 'Oğuz Atay', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Bozkurtlar', 'Hüseyin Nihal Atsız', 'Can Yayınları', 1);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Zamanımızın Bir Kahramanı', 'Mikhail Lermontov', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Küçük Prens', 'Antoine de Saint-Exupéry', 'Can Yayınları', 5);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Beyaz Gemi', 'Cengiz Aytmatov', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Gün Olur Asra Bedel', 'Cengiz Aytmatov', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Da Vinci Şifresi', 'Dan Brown', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Melekler ve Şeytanlar', 'Dan Brown', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Başlangıç', 'Dan Brown', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('İhanet Noktası', 'Dan Brown', 'Can Yayınları', 1);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Digital Kale', 'Dan Brown', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('İstanbul Hatırası', 'Ahmet Ümit', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Beyoğlu Rapsodisi', 'Ahmet Ümit', 'Can Yayınları', 4);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Kavim', 'Ahmet Ümit', 'Can Yayınları', 3);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Bab-ı Esrar', 'Ahmet Ümit', 'Can Yayınları', 2);
INSERT INTO KITAPLAR (ad, yazar, yayinevi, stok_sayisi) VALUES ('Patasana', 'Ahmet Ümit', 'Can Yayınları', 5);
